# FROM ubuntu:20.04 as build
FROM pratikimprowise/squid:5.1
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.1/s6-overlay-amd64-installer /tmp/
RUN chmod +x /tmp/s6-overlay-amd64-installer && /tmp/s6-overlay-amd64-installer / && rm -rf /tmp/s6-overlay-amd64-installer
# RUN adduser --disabled-login --no-create-home --disabled-password squid
RUN adduser squid
# RUN chown -cR squid /usr/local/squid/var/ && squid -z
# RUN mkdir -p /cache /etc/services.d/squid/ && chown -cR squid:squid /usr/local/squid/ /cache; \
RUN set -ex; \
  mkdir -p /etc/services.d/squid/; \
  # printf '/cache true squid:squid 0644 0755' >/etc/fix-attrs.d/01-squid-cache; \
  # printf '/usr/local/squid/var/ true squid:squid 0644 0755' >/etc/fix-attrs.d/02-squid-var; \
  printf '#!/usr/bin/with-contenv bash\nmkdir -p /cache\nchown -cR squid:squid /usr/local/squid/var/ /cache' >/etc/cont-init.d/3-config; \
  printf '#!/usr/bin/execlineb\ns6-envuidgid squid\ns6-applyuidgid -U\n/usr/local/squid/sbin/squid -z\n/usr/local/squid/sbin/squid --foreground -d 1;' >/etc/services.d/squid/run

# USER squid
# ENTRYPOINT ["/tini", "--"]
# CMD ["/usr/local/squid/sbin/squid","--foreground","-d","1"]
ENTRYPOINT ["/init"]

# FROM ubuntu:20.04 as build
# ARG VERSION=5.1
# ARG MAJOR_VERSION=5
# ARG TINI_VERSION=0.19.0
# ADD https://github.com/krallin/tini/releases/download/v$TINI_VERSION/tini /tini
# WORKDIR /app
# RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends \
#     --no-install-suggests -y \make gcc g++ wget tar grep gawk
# RUN wget --progress=dot:giga http://www.squid-cache.org/Versions/v$MAJOR_VERSION/squid-$VERSION.tar.gz
# RUN tar -xzf squid-*.tar.gz
# RUN cd squid-*; \
#  ./configure
# RUN make install -j$(nproc); \
#   chmod +x /tini; \
#   /usr/local/squid/sbin/squid -v

# FROM ubuntu:21.10
# ## for squid and squidclient
# ENV PATH="/usr/local/squid/sbin/:/usr/local/squid/bin/:${PATH}"

# COPY --from=build /tini /tini
# COPY --from=build /usr/local/squid /usr/local/squid
# ## give access to nobody
# RUN chmod o+rw -R /usr/local/squid/var/logs && squid -z
# ENTRYPOINT ["/tini", "--"]
# CMD ["squid","--foreground"]
