FROM ubuntu:20.04
ARG S6_VERSION=2.2.0.1
ADD https://github.com/just-containers/s6-overlay/releases/download/v$S6_VERSION/s6-overlay-amd64-installer /tmp/
ENV PATH="/usr/local/squid/sbin/:/usr/local/squid/bin/:${PATH}"
COPY root/ /
RUN set -ex; \
  chmod +x /tmp/s6-overlay-amd64-installer && /tmp/s6-overlay-amd64-installer /; \
  adduser --disabled-login --no-create-home --disabled-password squid
COPY --from=pratikimprowise/squid:build-dev-7726e12-202110071031126 /usr/local/squid /usr/local/squid
RUN apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends \
    --no-install-suggests -y libssl-dev ca-certificates openssl; \
    apt-get clean autoclean; \
    apt-get autoremove --yes; \
    rm -rf /var/lib/{apt,dpkg,cache,log}/
ENTRYPOINT ["/init"]
