#!/usr/bin/with-contenv bash

mkdir -p /usr/local/squid/etc/ssl

SSL_PATH="/usr/local/squid/etc/ssl"
SSL_PATH=${SSL_PATH%\/}
if [[ ! -f ${SSL_PATH}/CA.pem && ! -f ${SSL_PATH}/private.pem ]]; then
  echo "Generating new Certs"
  openssl req -new -newkey rsa:2048 -sha256 -days 9999 -nodes -x509 \
    -extensions v3_ca -keyout ${SSL_PATH}/private.pem \
    -out ${SSL_PATH}/private.pem \
    -subj "/O=Improwised/OU=DevOpsDept/C=IN/ST=Gujarat/L=Rajkot"

  openssl x509 -in ${SSL_PATH}/private.pem \
    -outform DER -out ${SSL_PATH}/CA.der

  openssl x509 -inform DER -in ${SSL_PATH}/CA.der \
    -out ${SSL_PATH}/CA.pem
else
  echo "Skipping Cert gen"
fi

ls ${SSL_PATH}
echo CA.pem
cat ${SSL_PATH}ca.pem
echo private.pem
cat ${SSL_PATH}private.pem

chown -cR squid:squid /usr/local/squid/etc/
