#!/usr/bin/with-contenv bash

SSL_PATH=${SSL_PATH:-"/etc/squid/ssl"}
SSL_PATH=${SSL_PATH%\/}

## Check for ssl certs
if [[ ! -f ${SSL_PATH}/CA.pem && ! -f ${SSL_PATH}/private.pem ]]; then
  echo "Cert not found" >&2
  exit 2
fi

## Show certs
ls -alt ${SSL_PATH}
echo CA.pem
head -n2 ${SSL_PATH}/CA.pem
echo private.pem
head -n2 ${SSL_PATH}/private.pem

## Dynamically create cache directory if exist in config
cachedir="$(grep ^cache_dir /etc/squid/squid.conf)"
if [ "${cachedir}" ]; then
  for dir in $(awk '{print$3}' <<<${cachedir}); do
    mkdir -p ${dir};
    chmod 777 -R ${dir}
  done
  squid -z --foreground 2>&1
fi

## Parse config file
squid -k parse 2>&1

## Init ssldb and fix permission
/usr/lib/squid/security_file_certgen -c -s /var/cache/squid/ssl_db -M 4MB
chmod 777 -R /var/cache/squid/
